---
# This is looped for each policy set of variables for the current vcenter outter loop

  - name: AssetGroup Post Folder Defaults - Include task
    include_tasks: tasks/vmworkflow_assetgroup_create_include.yml

  - name: debug asset group  id var from include task
    debug:
      msg: "{{assetgroup_id}}"
    when: assetgroup_id is defined


  - name: SLO Post Folder Default Protection Plan
    include_tasks: tasks/vmworkflow_slo_create.include.yml
    when: assetgroup_id is defined

  - name: debug SLO id var from include task
    debug:
      var: slo_id
    when: assetgroup_id is defined

  - name: AssetGroup Subscribe to SLO Post
    include_tasks: tasks/vmworkflow_subscribe.include.yml
    when: assetgroup_id is defined
